"""
update_leaderboard.py — Run the monogate symbolic regression benchmark and update
results/leaderboard.json + LEADERBOARD.md at the repo root.

Usage
-----
  python python/scripts/update_leaderboard.py                # all problems
  python python/scripts/update_leaderboard.py --fast         # n_sim=200, beam only
  python python/scripts/update_leaderboard.py --problems nguyen-1 nguyen-7 nguyen-8
  python python/scripts/update_leaderboard.py --n-sim 5000 --depth 6
"""

from __future__ import annotations

import argparse
import os
import sys

# Allow running from repo root: python python/scripts/update_leaderboard.py
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from monogate.leaderboard import (
    PROBLEMS,
    markdown_leaderboard,
    run_leaderboard,
    save_leaderboard,
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run monogate symbolic regression leaderboard"
    )
    parser.add_argument(
        "--problems",
        nargs="+",
        default=None,
        metavar="NAME",
        help="Problem names to run (default: all). E.g. nguyen-1 nguyen-7",
    )
    parser.add_argument(
        "--n-sim",
        type=int,
        default=2000,
        dest="n_sim",
        help="MCTS/beam simulations per problem (default: 2000)",
    )
    parser.add_argument(
        "--depth",
        type=int,
        default=5,
        help="Maximum EML tree depth (default: 5)",
    )
    parser.add_argument(
        "--methods",
        nargs="+",
        default=["mcts", "beam"],
        choices=["mcts", "beam"],
        help="Search methods to use (default: mcts beam)",
    )
    parser.add_argument(
        "--fast",
        action="store_true",
        help="Fast mode: n_sim=200, beam only — useful for CI smoke tests",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed (default: 42)",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        dest="out_dir",
        help="Output directory for leaderboard.json (default: python/results/)",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    if args.fast:
        n_sim = 200
        methods = ["beam"]
    else:
        n_sim = args.n_sim
        methods = args.methods

    problems = args.problems or list(PROBLEMS.keys())

    print(f"monogate leaderboard — {len(problems)} problems × {len(methods)} methods")
    print(f"n_sim={n_sim}, depth={args.depth}, seed={args.seed}")
    print()

    entries = run_leaderboard(
        problems=problems,
        n_simulations=n_sim,
        depth=args.depth,
        methods=methods,
        seed=args.seed,
    )

    # Determine output paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    python_dir = os.path.dirname(script_dir)
    repo_root = os.path.dirname(python_dir)

    if args.out_dir:
        results_dir = args.out_dir
    else:
        results_dir = os.path.join(python_dir, "results")

    os.makedirs(results_dir, exist_ok=True)
    json_path = os.path.join(results_dir, "leaderboard.json")
    md_path = os.path.join(repo_root, "LEADERBOARD.md")

    save_leaderboard(entries, json_path)
    print(f"Saved: {json_path}")

    # Write LEADERBOARD.md
    solved = sum(1 for e in entries if e.solved)
    total = len(entries)
    md_content = f"""# monogate Symbolic Regression Leaderboard

Benchmark: {len(problems)} problems from the Nguyen/Keijzer suite.
Search: {', '.join(methods)} | n_sim={n_sim} | depth={args.depth}
Solved: {solved}/{total} ({100*solved//total if total else 0}%)

{markdown_leaderboard(entries)}

---
*Generated by `python/scripts/update_leaderboard.py`*
"""
    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write(md_content)
    print(f"Saved: {md_path}")

    # Print summary table
    print()
    print(markdown_leaderboard(entries))
    print()
    print(f"Solved: {solved}/{total}")


if __name__ == "__main__":
    main()
